version: '3'

services:
  db:
    image: microsoft/mssql-server-windows-express
    volumes:
      - .\data\databases:C:\Data 
    environment:
      ACCEPT_EULA: Y
      sa_password: Docker+Sitecore!
      attach_dbs: "[{'dbName':'Sitecore_Core','dbFiles':['C:\\\\Data\\\\Sitecore.Core.mdf','C:\\\\Data\\\\Sitecore.Core.ldf']},{'dbName':'Sitecore_Master','dbFiles':['C:\\\\Data\\\\Sitecore.Master.mdf', 'C:\\\\Data\\\\Sitecore.Master.ldf']},{'dbName': 'Sitecore_Web', 'dbFiles': ['C:\\\\Data\\\\Sitecore.Web.mdf','C:\\\\Data\\\\Sitecore.Web.ldf']},{'dbName':'Sitecore_Analytics','dbFiles':['C:\\\\Data\\\\Sitecore.Analytics.mdf','C:\\\\Data\\\\Sitecore.Analytics.ldf']}]"

  webapp:
    ports:
      - "80"
    volumes:
      - .\data\serialization:C:\Sitecore\Data\serialization
      - .\data\logs:C:\Sitecore\Data\logs
    links: 
      - db

networks:
  default:
    external:
      name: nat
